### PR TITLE
feat: update react & react-dom to v17

### PR DESCRIPTION
**Pull request by Mashal-m**
## Ticket
[Upgrade React JS to v17](https://github.com/openedx/frontend-component-cookie-policy-banner/issues/426)

### Description

- Updated `react` & `react-dom` to v17,  along with `@storybook/addon-a11y` to respective compatible versions
- Since Enzyme does not provide support React 17 ([enzymejs/enzyme#2429](https://github.com/enzymejs/enzyme/issues/2429)) or 18 ([enzymejs/enzyme#2524](https://github.com/enzymejs/enzyme/issues/2524)) itself we switched to community-supported project that aim to provide compatibility between Enzyme and React 17, replacing `enzyme-adapter-react-16` with `@wojtekmaj/enzyme-adapter-react-17`

### CODE REVIEW

**Comment by Mashal-m** [comment]
> Just curious, why not straight to React 18? Too much breaking changes?

Yes because of breaking changes, we are planning to upgrade React 18 after React 17.

**Comment by jmbowman** [comment]
Is anything blocking progress on this?  I don't see any reviewers assigned.

**Comment by Mashal-m** [comment]
@Toxicom could you please merge this?

**Review by feanil — APPROVED** [review]
This looks like a reasonable update and tests are passing.

**Pull request merged**
